# -*- coding: utf-8 -*-
"""Project 130

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P1S-aH4EtQd04Kq74haU0Crb11HnjDRi
"""

import pandas as pd
df = pd.read_csv("total_stars.csv")
df.columns
df.drop(['Unnamed: 0','Unnamed: 6', 'Star_name.1', 'Distance.1', 'Mass.1', 'Radius.1','Luminosity'], axis = 1, inplace = True)
finaldata = df.dropna()
finaldata.reset_index(drop = True, inplace = True)
finaldata.to_csv("finalstars.csv")
finaldata.info()
finaldata.describe()